"""Add dasi_id

Revision ID: 08cbff4652e8
Revises: 12c0db4c9dff
Create Date: 2025-01-25 21:23:00.540017

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08cbff4652e8'
down_revision = '12c0db4c9dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epigraph', sa.Column('dasi_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epigraph', 'dasi_id')
    # ### end Alembic commands ###
