"""Add taskprog

Revision ID: 03547754cd9d
Revises: 6e4d138af4ab
Create Date: 2025-01-26 01:59:39.488523

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '03547754cd9d'
down_revision = '6e4d138af4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskprogress',
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('uuid', 'id')
    )
    op.create_index(op.f('ix_taskprogress_id'), 'taskprogress', ['id'], unique=False)
    op.create_index(op.f('ix_taskprogress_uuid'), 'taskprogress', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskprogress_uuid'), table_name='taskprogress')
    op.drop_index(op.f('ix_taskprogress_id'), table_name='taskprogress')
    op.drop_table('taskprogress')
    # ### end Alembic commands ###
