"""Make some site fields non-nullable

Revision ID: 040824eb485d
Revises: 92baa5845a53
Create Date: 2025-04-25 00:16:50.764926

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '040824eb485d'
down_revision = '92baa5845a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('site', 'modern_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('site', 'ancient_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('site', 'license',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'license',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('site', 'ancient_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('site', 'modern_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('site', 'uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
