"""Add word and epigraph link

Revision ID: 06bdc66f9278
Revises: aba9441d31b5
Create Date: 2025-02-21 00:28:22.252198

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '06bdc66f9278'
down_revision = 'aba9441d31b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_id'], ['word.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epigraphwordlink',
    sa.Column('epigraph_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['epigraph_id'], ['epigraph.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('epigraph_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epigraphwordlink')
    op.drop_table('word')
    # ### end Alembic commands ###
