"""Add taskprogress skipped items

Revision ID: 07f947afe329
Revises: b32c56862f3d
Create Date: 2025-08-07 22:36:30.551250

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector


# revision identifiers, used by Alembic.
revision = '07f947afe329'
down_revision = 'b32c56862f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskprogress', sa.Column('skipped_items', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskprogress', 'skipped_items')
    # ### end Alembic commands ###
