"""Add position of word within epigraph to epigraphwordlink

Revision ID: 0c6badb7d447
Revises: e365be68862d
Create Date: 2026-06-05 21:19:26.572090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector


# revision identifiers, used by Alembic.
revision = '0c6badb7d447'
down_revision = 'e365be68862d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epigraphwordlink', sa.Column('positions', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epigraphwordlink', 'positions')
    # ### end Alembic commands ###
