"""Make some epigraph fields optional

Revision ID: 108932aa3149
Revises: 196a2db69ca8
Create Date: 2025-01-29 23:38:31.085336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '108932aa3149'
down_revision = '196a2db69ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('epigraph', 'uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('epigraph', 'epigraph_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('epigraph', 'chronology_conjectural',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('epigraph', 'language_level_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('epigraph', 'textual_typology_conjectural',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('epigraph', 'royal_inscription',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('epigraph', 'license',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'license',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('epigraph', 'royal_inscription',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('epigraph', 'textual_typology_conjectural',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('epigraph', 'language_level_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('epigraph', 'chronology_conjectural',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('epigraph', 'epigraph_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('epigraph', 'uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('epigraph', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
