"""Update letter_measure to str

Revision ID: 196a2db69ca8
Revises: 799902a13970
Create Date: 2025-01-28 22:43:01.792708

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '196a2db69ca8'
down_revision = '799902a13970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'letter_measure',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'letter_measure',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
