"""Rename last_modified

Revision ID: 52660d0c6cf6
Revises: d758c954a648
Create Date: 2025-04-26 02:09:11.302933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52660d0c6cf6'
down_revision = 'd758c954a648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'last_modified_dasi', new_column_name='last_modified')
    op.alter_column('site', 'last_modified_dasi', new_column_name='last_modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'last_modified', new_column_name='last_modified_dasi')
    op.alter_column('site', 'last_modified', new_column_name='last_modified_dasi')
    # ### end Alembic commands ###
