"""Add word classification and attrs, update relations

Revision ID: 6e2602ffce17
Revises: 06bdc66f9278
Create Date: 2025-02-22 02:26:21.023498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e2602ffce17'
down_revision = '06bdc66f9278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlink',
    sa.Column('from_word_id', sa.Integer(), nullable=False),
    sa.Column('to_word_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_word_id'], ['word.id'], ),
    sa.ForeignKeyConstraint(['to_word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('from_word_id', 'to_word_id')
    )
    op.add_column('word', sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('word', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('word', sa.Column('frequency', sa.Integer(), nullable=False))
    op.drop_constraint('word_next_id_fkey', 'word', type_='foreignkey')
    op.drop_constraint('word_previous_id_fkey', 'word', type_='foreignkey')
    op.drop_column('word', 'next_id')
    op.drop_column('word', 'previous_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('previous_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('word', sa.Column('next_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('word_previous_id_fkey', 'word', 'word', ['previous_id'], ['id'])
    op.create_foreign_key('word_next_id_fkey', 'word', 'word', ['next_id'], ['id'])
    op.drop_column('word', 'frequency')
    op.drop_column('word', 'attributes')
    op.drop_column('word', 'classification')
    op.drop_table('wordlink')
    # ### end Alembic commands ###
