"""Make dasi_idnot null

Revision ID: 6e4d138af4ab
Revises: 08cbff4652e8
Create Date: 2025-01-25 21:37:12.558952

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6e4d138af4ab'
down_revision = '08cbff4652e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'dasi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'dasi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
