"""Add images

Revision ID: 6f57fe13d567
Revises: 0de0dbf3f22a
Create Date: 2025-07-05 13:04:36.796125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f57fe13d567'
down_revision = '0de0dbf3f22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epigraph', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epigraph', 'images')
    # ### end Alembic commands ###
