"""Add Epigraph fields with temp optional

Revision ID: 799902a13970
Revises: 03547754cd9d
Create Date: 2025-01-28 01:51:58.007044

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '799902a13970'
down_revision = '03547754cd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epigraph', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('epigraph_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('chronology_conjectural', sa.Boolean(), nullable=True))
    op.add_column('epigraph', sa.Column('mentioned_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('sites', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('language_level_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('language_level_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('language_level_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('alphabet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('script_typology', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('script_cursus', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('textual_typology', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('textual_typology_conjectural', sa.Boolean(), nullable=True))
    op.add_column('epigraph', sa.Column('letter_measure', sa.Float(), nullable=True))
    op.add_column('epigraph', sa.Column('writing_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('royal_inscription', sa.Boolean(), nullable=True))
    op.add_column('epigraph', sa.Column('cultural_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('aparatus_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('general_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('bibliography', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('concordances', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('first_published', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('epigraph', sa.Column('editors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('epigraph', sa.Column('last_modified_dasi', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epigraph', 'last_modified_dasi')
    op.drop_column('epigraph', 'editors')
    op.drop_column('epigraph', 'first_published')
    op.drop_column('epigraph', 'license')
    op.drop_column('epigraph', 'concordances')
    op.drop_column('epigraph', 'bibliography')
    op.drop_column('epigraph', 'general_notes')
    op.drop_column('epigraph', 'aparatus_notes')
    op.drop_column('epigraph', 'cultural_notes')
    op.drop_column('epigraph', 'royal_inscription')
    op.drop_column('epigraph', 'writing_techniques')
    op.drop_column('epigraph', 'letter_measure')
    op.drop_column('epigraph', 'textual_typology_conjectural')
    op.drop_column('epigraph', 'textual_typology')
    op.drop_column('epigraph', 'script_cursus')
    op.drop_column('epigraph', 'script_typology')
    op.drop_column('epigraph', 'alphabet')
    op.drop_column('epigraph', 'language_level_3')
    op.drop_column('epigraph', 'language_level_2')
    op.drop_column('epigraph', 'language_level_1')
    op.drop_column('epigraph', 'sites')
    op.drop_column('epigraph', 'mentioned_date')
    op.drop_column('epigraph', 'chronology_conjectural')
    op.drop_column('epigraph', 'period')
    op.drop_column('epigraph', 'translations')
    op.drop_column('epigraph', 'epigraph_text')
    op.drop_column('epigraph', 'uri')
    op.drop_column('epigraph', 'title')
    # ### end Alembic commands ###
