"""Add object/site dasi_published, make epigraph lang level 1 optional

Revision ID: 894dcca60d9d
Revises: 8bdceddb934c
Create Date: 2025-05-06 15:24:10.266662

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '894dcca60d9d'
down_revision = '8bdceddb934c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('epigraph', 'language_level_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('object', sa.Column('dasi_published', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('dasi_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'dasi_published')
    op.drop_column('object', 'dasi_published')
    op.alter_column('epigraph', 'language_level_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
