"""Remove UUID from analytics_cache

Revision ID: 8ab696e0f0b5
Revises: 894dcca60d9d
Create Date: 2025-05-14 00:05:25.993249

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ab696e0f0b5'
down_revision = '894dcca60d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyticscache_uuid', table_name='analyticscache')
    op.drop_column('analyticscache', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyticscache', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.create_index('ix_analyticscache_uuid', 'analyticscache', ['uuid'], unique=True)
    # ### end Alembic commands ###
