"""Add epigraph dasi_published

Revision ID: 8bdceddb934c
Revises: f29ab598b04b
Create Date: 2025-05-06 03:35:16.834179

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8bdceddb934c'
down_revision = 'f29ab598b04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epigraph', sa.Column('dasi_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('epigraph', 'dasi_published')
    # ### end Alembic commands ###
