"""Add epigraphchunk

Revision ID: 8d831eabbe4c
Revises: 07f947afe329
Create Date: 2025-10-24 23:45:28.741549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d831eabbe4c'
down_revision = '07f947afe329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epigraphchunk',
    sa.Column('epigraph_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['epigraph_id'], ['epigraph.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epigraphchunk_chunk_type'), 'epigraphchunk', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_epigraphchunk_epigraph_id'), 'epigraphchunk', ['epigraph_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epigraphchunk_epigraph_id'), table_name='epigraphchunk')
    op.drop_index(op.f('ix_epigraphchunk_chunk_type'), table_name='epigraphchunk')
    op.drop_table('epigraphchunk')
    # ### end Alembic commands ###
