"""Add site fields

Revision ID: 92baa5845a53
Revises: 2ae8dfb68c1a
Create Date: 2025-04-25 00:07:56.856896

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92baa5845a53'
down_revision = '2ae8dfb68c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('modern_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('ancient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('governorate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('geographical_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('editors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('first_published', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('last_modified_dasi', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'last_modified_dasi')
    op.drop_column('site', 'first_published')
    op.drop_column('site', 'license')
    op.drop_column('site', 'editors')
    op.drop_column('site', 'geographical_area')
    op.drop_column('site', 'governorate')
    op.drop_column('site', 'country')
    op.drop_column('site', 'ancient_name')
    op.drop_column('site', 'modern_name')
    op.drop_column('site', 'uri')
    # ### end Alembic commands ###
