"""Add AnalyticsCache

Revision ID: aba9441d31b5
Revises: 108932aa3149
Create Date: 2025-02-19 23:45:07.207584

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aba9441d31b5'
down_revision = '108932aa3149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyticscache',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('uuid', 'id')
    )
    op.create_index(op.f('ix_analyticscache_id'), 'analyticscache', ['id'], unique=False)
    op.create_index(op.f('ix_analyticscache_key'), 'analyticscache', ['key'], unique=False)
    op.create_index(op.f('ix_analyticscache_uuid'), 'analyticscache', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyticscache_uuid'), table_name='analyticscache')
    op.drop_index(op.f('ix_analyticscache_key'), table_name='analyticscache')
    op.drop_index(op.f('ix_analyticscache_id'), table_name='analyticscache')
    op.drop_table('analyticscache')
    # ### end Alembic commands ###
