"""Update object required fields

Revision ID: d758c954a648
Revises: eb7410ddd16b
Create Date: 2025-04-25 23:55:13.022708

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd758c954a648'
down_revision = 'eb7410ddd16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('object', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('object', 'uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('object', 'license',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('object', 'license',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('object', 'uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('object', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
