"""Add language to word

Revision ID: e365be68862d
Revises: f4f7a1c2d9e0
Create Date: 2026-06-01 23:28:47.171279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector


# revision identifiers, used by Alembic.
revision = 'e365be68862d'
down_revision = 'f4f7a1c2d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('language_level_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('word', sa.Column('language_level_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('word', sa.Column('language_level_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'language_level_3')
    op.drop_column('word', 'language_level_2')
    op.drop_column('word', 'language_level_1')
    # ### end Alembic commands ###
