"""Add additional object fields

Revision ID: eb7410ddd16b
Revises: 040824eb485d
Create Date: 2025-04-25 23:21:50.457087

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb7410ddd16b'
down_revision = '040824eb485d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('deposits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('object', sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('object', sa.Column('shape', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('measures', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('decorations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('object', sa.Column('support_type_level_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('support_type_level_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('support_type_level_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('support_type_level_4', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('support_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('deposit_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('cultural_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('object', sa.Column('bibliography', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('object', sa.Column('concordances', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('object', sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('editors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('object', sa.Column('first_published', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('object', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'last_modified')
    op.drop_column('object', 'first_published')
    op.drop_column('object', 'editors')
    op.drop_column('object', 'license')
    op.drop_column('object', 'concordances')
    op.drop_column('object', 'bibliography')
    op.drop_column('object', 'cultural_notes')
    op.drop_column('object', 'deposit_notes')
    op.drop_column('object', 'support_notes')
    op.drop_column('object', 'support_type_level_4')
    op.drop_column('object', 'support_type_level_3')
    op.drop_column('object', 'support_type_level_2')
    op.drop_column('object', 'support_type_level_1')
    op.drop_column('object', 'decorations')
    op.drop_column('object', 'measures')
    op.drop_column('object', 'shape')
    op.drop_column('object', 'materials')
    op.drop_column('object', 'deposits')
    op.drop_column('object', 'period')
    op.drop_column('object', 'end_date')
    op.drop_column('object', 'start_date')
    op.drop_column('object', 'uri')
    op.drop_column('object', 'title')
    # ### end Alembic commands ###
