"""Add additional site fields

Revision ID: f29ab598b04b
Revises: 52660d0c6cf6
Create Date: 2025-05-03 16:49:03.858381

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f29ab598b04b'
down_revision = '52660d0c6cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('coordinates_accuracy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('location_and_toponomy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('type_of_site', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('general_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('bibliography', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('classical_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('archaeological_missions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('travellers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('history_of_research', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('chronology', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('monuments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('structures', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('deities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('tribe', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('identification', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('site', sa.Column('kingdom', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'language')
    op.drop_column('site', 'kingdom')
    op.drop_column('site', 'identification')
    op.drop_column('site', 'tribe')
    op.drop_column('site', 'deities')
    op.drop_column('site', 'structures')
    op.drop_column('site', 'monuments')
    op.drop_column('site', 'chronology')
    op.drop_column('site', 'history_of_research')
    op.drop_column('site', 'travellers')
    op.drop_column('site', 'archaeological_missions')
    op.drop_column('site', 'classical_sources')
    op.drop_column('site', 'bibliography')
    op.drop_column('site', 'notes')
    op.drop_column('site', 'general_description')
    op.drop_column('site', 'type_of_site')
    op.drop_column('site', 'location_and_toponomy')
    op.drop_column('site', 'coordinates_accuracy')
    op.drop_column('site', 'coordinates')
    # ### end Alembic commands ###
